export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const DESIGN_LIST_SUCCESS = 'DESIGN_LIST_SUCCESS'
export const ADD_DESIGN = 'ADD_DESIGN'